logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: INFO
    java.sql: DEBUG

spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp


server:
  port: 8080
